<a href="https://colab.research.google.com/github/JhonathanOrtiz/FreeCodeCampCourse/blob/master/FreeCodeCampCourse_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

### PERO ¿QUE RAYOS ES UN TENSOR?

Para nosotros en inteligencia artificial y machine learning un tensor es un contenedor en el cual podemos almacenar números, ¿Como una matriz o un vector? si como en una matriz o un vector.

¿Quieres saber la diferencia entre una matriz y un tensor [aquí](https://math.stackexchange.com/questions/412423/what-are-the-differences-between-a-matrix-and-a-tensor)
esta una muy buena manera de saberlo.

### What's a Tensor?

A tensor is an object that allow us store numbers, Like an array? yes, like an array or vector.

Do you want know more about tensor a diference between tensors and Matrix? 
Click [here](https://math.stackexchange.com/questions/412423/what-are-the-differences-between-a-matrix-and-a-tensor)

In [16]:
t1 = torch.tensor(1.)
print(t1)
t1.dtype

tensor(1.)


torch.float32

En python nosotros podemos poner un punto al final de un número para indicar que el mismo es un numero floante. En éste caso creamos un numero tensor de un escalar. 

Ahora veamos como crear otros contenedores de datos.

In python we can write a number followed by a dot, in this case we're indicate that number like a float number.

Now, let`s see another data container.

In [19]:
#Vector tensor
t2 =  torch.tensor([1, 2., 5, 6])
print('Tensor shape {}'.format(t2.shape))
print('')
t2

Tensor shape torch.Size([4])



tensor([1., 2., 5., 6.])

In [23]:
#2D Matrix Tensor
t3 = torch.tensor([[1, 2, 3], 
                   [2, 5, 6.]])
print('Tensor shape {}'.format(t3.shape))
print('')
t3

Tensor shape torch.Size([2, 3])



tensor([[1., 2., 3.],
        [2., 5., 6.]])

In [30]:
#3D matrix Tensor
t4 =  torch.tensor([[[1, 2, 3], [3, 2, 1]],
                    [[1, 5, 3], [1, 4, 5]]])

print('Tensor shape {}'.format(t4.shape))
print('')
t4

Tensor shape torch.Size([2, 2, 3])



tensor([[[1, 2, 3],
         [3, 2, 1]],

        [[1, 5, 3],
         [1, 4, 5]]])

### Operation and gradients

We will need to associate tensors to compute our output from input, for this we can use the basic operator like '+' '-' or '*'. Example The image are readed like numpy ndarray and pytorch models works only with tensors. Remember this I CAN'T WORK WITH NUMPY ARRAY ON PYTORCH. We will see how to work with numpy array and tensor.

The gradients are computed in Machine learning and Deep learing to teach to our model relationship between the data and the output to make accurate predictions. For this Pytorch has Automatic Diferentiation and compute darivatives automatically.

For the people is Artificial Intelligence for us Diferentiable Programming

### Gradientes y operaciones

Necesitaresmos asociar tensores para calcular las predicciones del modelo y para ello podemos usar operadores básicos conocidos como '+', '-' or '*'. Un ejemplo, las imagenes muchas veces como numpy ndarray y no podemos pasar a un modelo de pytorch un numpy ndarray para ello veremos como trabajar entre matrices y tensores, solo recuerda 'NO PUEDO USAR NUMPY ARRAYS CON TENSORES' 


Los gradientes son calculados en Machine Learning enseñar a nuestro modelos relaciones entre los datos y la salida, para ello pytorch nos provee la Auto-diferenciacion y automaticamente nos cálcula derivadas.

Para la personas es Inteligencia Artificial y para nosotros Programacion Diferenciable.

In [35]:
x = np.array([1,])
y = torch.tensor([3])

print(x + y)

TypeError: ignored

As you can see is impossible associate a tensor and numpy ndarray, and **What's the solcution?** Pytorch is our friend.

Como puedes ver no podemos asociar tensores y numpy ndarray **¿Cuál es la solución?** Pytorch es nuestro amigo. 

In [42]:
#Solution!!!
#From numpy to tensor
t = torch.from_numpy(x)
print('Tensor sum {}.'.format(t + y))
print('DType x: {}'.format(type(x)))
print('New DType x: {}'.format(type(t)))

Tensor sum tensor([4]).
DType x: <class 'numpy.ndarray'>
New DType x: <class 'torch.Tensor'>


In [43]:
#From tensor to numpy ndarray
n = t.numpy()
type(n)

numpy.ndarray

## NOTE

To show image with matplotlib for example, the array should be numpy ndaaray not a tensor.

## NOTA

Para mostrar imagenes con matplotlib por ejemplo el array deberá ser un numpy ndarray no un tensor.

In [48]:
m = torch.tensor([10.])
b = torch.tensor([5.], requires_grad=True)
X = torch.tensor([3.], requires_grad=True)

y = m * X + b
y

tensor([35.], grad_fn=<AddBackward0>)

Nothing new the result is 35 as we expected, so the awesome is that Pytorch compete automatically the derivatives y if *Requires_grad* is turn True and to compute this derivative only we should call to .backward method.

Nada nuevo hasta ahora y el resultado como esperabamos es 35, pero lo asombroso es que Pytorch calcula automaticamente la derivada de **y** con solo poner en True el argumento *requieres_grad* y para calcular las dereivadas solo debemos llamar al metodo .backward.

In [0]:
y.backward()

Now the derivatives are stored in the .grad propety of the respective tensors

Ahora las derivadas son almacenadas en la propiedad .grad de cada tensor

In [51]:
print('dy/dx: ', X.grad)
print('dy/dm: ', m.grad)
print('dy/db: ', b.grad)

dy/dx:  tensor([10.])
dy/dm:  None
dy/db:  tensor([1.])


dy/dx is none because *requieres_grad* is not defined True.

dy/dx es none porque requieres_grad no se definió como True

In [55]:
!pip install jovian